# LEARNINGS — 歷任 session 踩坑紀錄

> 每個 session 開始時讀本檔。格式與精簡規則見 agents/MAINTENANCE.md §3–§4。
> 已固化進制度檔的教訓不在此重複。上次精簡：2026-07-15（17→12 條）。

- [2026-07-07] 情境：派 verifier/applier 自訂 agent｜事實：**已確認可用**——.claude/agents/*.md 會被載入，但建立當下不會立即生效（同 session 內隔幾個回合、清單刷新後才出現；剛建立就派用會回「Agent type not found」）｜規則：直接用 subagent_type: verifier / applier；清單暫時沒有就用 general-purpose + agents/TEMPLATES.md T5 代替。
- [2026-07-07] 情境：在 avi-v5 或本環境裝 pip 依賴｜錯誤：`pip install -r requirements.txt` 撞 debian 系統套件衝突（PyJWT RECORD file not found）｜正解：加 `--user`｜規則：本環境 pip 安裝一律用 `pip install --user`。
- [2026-07-07] 情境：Bash 工具跨呼叫的工作目錄會延續｜錯誤：上一個指令 cd 進子目錄後，下一個指令用相對路徑找不到檔案｜正解：一律用絕對路徑（/home/user/KIWI/...）｜規則：Bash 指令不依賴前一次呼叫留下的 cwd。
- [2026-07-10] 情境：查證外部網站與鏈上數據｜事實：WebFetch 可用性**依環境網路政策而定**——某些 session 整體 403（連 example.com 都擋），但 2026-07-15 這個 session 對 github.com／raw.githubusercontent.com WebFetch 正常；agent proxy 對多數外站（polymarket、etherscan、t.me、x.com 等）CONNECT 常 403｜正解：先試 WebFetch，被 403 才退 WebSearch 多來源交叉；數字標「快照非即時」，頁面級驗證回寫 mac-manual-homework｜規則：不要預設全站皆擋、也不要浪費回合硬試已知擋的站；查證派 subagent。
- [2026-07-10] 情境：push 後 GitHub Actions 毫無反應（run 數 0、workflow 未註冊）｜錯誤：commit 訊息的說明文字裡含字面 [skip ci]（描述防迴圈機制），GitHub 對訊息任何位置的 [skip ci]/[ci skip] 都會跳過觸發｜正解：推一個乾淨訊息、且觸及 workflow paths 過濾的 commit 重新觸發｜規則：commit 訊息絕不出現字面 [skip ci]，要描述機制就寫「skip-ci 標記」。
- [2026-07-10] 情境：用 Polymarket activity feed 重建錢包已實現 PnL 做跟單模擬｜錯誤：直接 recovered(SELL+REDEEM)−cost(BUY) 得出 300%+ ROI、100% 勝率的假獲利｜事實：(1) 輸的部位不產生 REDEEM 事件（只有贏了領獎才有）→ 重建 PnL 系統性只看到贏家、嚴重高估；(2) 高頻錢包 activity 1500 筆上限只涵蓋約 12h，視窗內「只結算無買入」的幽靈市場把前期建倉獲利當 cost=0 純利｜正解：只算「買入+出場都在視窗內」的完整 round-trip；截斷+短窗+結算全為贏家時工具要明白拒答（reliable=False）｜規則：凡從交易流重建績效，先問「輸家看得到嗎、視窗夠長嗎」，唯一可信 PnL 來源是 user-pnl-api 曲線。
- [2026-07-10] 情境：使用者明確要求回覆語言｜事實：Jake 要求**所有對他的回覆一律用繁體中文**（除非他特別指定其他語言）；工作中曾漂移成英文被糾正｜正解：每個 session 全程繁體中文回覆，程式碼/指令/專有名詞可保留英文｜規則：對使用者的所有訊息以繁體中文撰寫，不因模型切換或上下文語言漂移。
- [2026-07-10] 情境：CI commit-back 把 36MB 的 leaderboard 原始回應整包 commit 進 repo（且每日排程會重複）｜錯誤：fetch 落地原始 API 回應前沒檢查大小｜正解：大型原始回應在 CI 工作區就地消化成衍生摘要，版控只收 <1MB 的摘要/報告；已發生的肥 commit 在分支未合併前用 reset+重組提交移除｜規則：任何 CI 會自動 commit 的產物，落地前先估大小；>1MB 就先瘦身再入版控。
- [2026-07-10] 情境：兩支 CI workflow 各自 commit-back 到同一分支｜錯誤：hyper 掃描跑 14 分鐘期間 poly-shadow 先推了 commit，hyper 的裸 git push 被拒→整份掃描報告隨 runner 回收消失｜正解：所有 commit-back 段在 push 前加 `git pull --rebase origin "${GITHUB_REF_NAME}"`｜規則：多 workflow 寫同分支，commit-back 一律 rebase-then-push。
- [2026-07-12] 情境：新增 GitHub Actions workflow 檔｜事實：遠端 session 的整合 token **可以**直接 git push 含 .github/workflows/ 新檔的 commit（實證成功，agenda-reminder.yml）；但 cron schedule 只在 default branch 生效｜規則：feature branch 上新增的排程 workflow，要明白提醒使用者「合併 main 才會開始跑」。
- [2026-07-12] 情境：呼叫 claude-code-remote MCP server 的工具（list_repos、add_repo、send_later、create_trigger 等）｜事實：這個 surface 對整組工具不是回「not available for account-owned sessions」（list_repos）就是「requires approval」的連線層卡住（add_repo/send_later，非使用者拒絕、核准流程未觸達使用者、重試無用）｜正解：要 repo metadata 改用 mcp__github__* 工具；排程/推播用檔案落地替代｜規則：claude-code-remote 工具失敗即回報使用者並用替代方案，不重試第二次（本 session 曾見它們一度斷線又重連，可用性依 surface/連線狀態而定）。
- [2026-07-26] 情境：Serenity 週報重定價（抓全名單現價/市值/P/E）｜錯誤：一直用 WebSearch snippet 當主源，結果 07-22 週報有 **9 檔價格誤植**（Koh Young 誤 +59%、Intekplus 誤 −54%、FORM +22%、Towa +18%、Mersen +12%…），還憑錯值產出「Koh Young +20.2%🚩 反漲脫離累積區」「PLAB +16.6%🚩 近 $2B」等假觸發判定｜事實：**GitHub Actions runner 不受雲端 proxy 封鎖，可用 Bash curl 直連 Yahoo Finance 行情 API**——①日線：`https://query2.finance.yahoo.com/v8/finance/chart/<SYM>?range=2mo&interval=1d`（**用 query2，query1 會 429**；`meta.regularMarketPrice` 才有最新收盤，日線 bar 可能少最後一天）②市值/P/E/現金：`/v10/finance/quoteSummary/<SYM>?modules=price,defaultKeyStatistics,summaryDetail,financialData&crumb=<CRUMB>`，crumb 取法＝先 GET `https://fc.yahoo.com/` 拿 cookie 再 GET `/v1/test/getcrumb`（需帶 cookie jar 與桌面 UA；HTTP 錯誤要自己吞，fc.yahoo.com 會回 404 但 cookie 已拿到）③每檔間隔 ~1.5s、失敗退避 6s，46 檔約 2 分鐘（用 `nohup ... &` 背景跑，別卡 2 分鐘 timeout）④JP/KR/TW 代碼＝`6855.T`／`098460.KQ`／`000660.KS`／`6664.TWO`／`2408.TW`，匯率＝`JPY=X`｜規則：**凡需要精確價格/市值的任務（週報重定價、觸發判定），一律先用這條 API 路徑當主源，WebSearch 只作交叉驗證與「為什麼動」的敘事來源**。Yahoo 的 `forwardPE` 對日韓小型股嚴重失真（Seikoh 124.9×、Advantest 121.8×、Towa 14.8× vs 研究值 28×），**只用 trailingPE/marketCap，forward P/E 一律標 [推論] 且不作觸發依據**。
- [2026-07-27] 情境：把「雲端抓不到」的資料搬進 GitHub Actions 資料橋｜錯誤：`fetch_jp_disclosures.py` 側掛成功、runner 也抓得到，但落地的 `.md` **從未進版控**——`update-dashboard.yml` 的 commit 段只有 `git add projects/avi-v5/data/ext/*.csv`，`.md` 不被該 glob 涵蓋，每次抓完隨 runner 回收消失，整整一天沒人發現（同 2026-07-10 那個「報告隨 runner 消失」的坑，換了個外衣）｜正解：補一行 `git add <新落地路徑>`；且驗收資料橋不能只看「腳本有沒有跑」，要看**檔案有沒有出現在 repo**｜規則：**新增任何資料橋產出路徑後，立刻確認它被某個 `git add` glob 涵蓋**——沒被 commit 的產出等於沒做；驗收句一律是「repo 裡有沒有這個檔」，不是「腳本有沒有成功」。
- [2026-07-28] 情境：在工作分支上判斷「某條資料管線是不是停更了」｜錯誤：直接讀工作區的 `candidates_latest.json`，看到 `generated_at` 停在 07-24 就寫成待辦「tw-funnel 停更 3 天，去查 Actions」——實際上管線好好的，只是**工作分支比 main 舊 12 個自動 commit**（每日 bot 一直在推 main），且 07-24(五)→07-27(一) 的空檔本來就是週末無交易日｜正解：合併 main 後 `generated_at` 是 07-27T12:46Z，誤報已撤回｜規則：**判斷資料新鮮度前先 `git fetch origin main` 並用 `git log --oneline -3 -- <資料路徑>` 看該路徑的最新 commit**，不要只看工作區檔案內容的時間戳——本 repo 的 main 每天被自動 commit 推進，任何存活超過一天的分支看到的資料都是舊的。另外：判定「停更」前先確認那幾天是不是**週末或非交易日**。
- [2026-07-27] 情境：撰寫含具體數值門檻的操作手冊（出場手冊 v1，21 條機械條件）｜錯誤：三處「聽起來很合理」的具體內容其實無出處——①村田「受注残比 <1.0」是憑空生出的門檻（原文只有現值 1.27／2018 峰 1.25）②CRI ELEVATED 的動作文字混用兩處行號、且含一句全檔 Grep 查無的措辭 ③T3 買回的 P/B 數字引用行號錯置（在 `:70-71` 不在 `:104`）｜正解：派 fresh-context verifier 逐條核對「手冊寫什麼 vs 原檔實際寫什麼」，三處全被抓出；修正時**保留自訂數字但明白標註「此門檻為自訂、無出處、待確認」**，而不是刪掉或假裝有出處｜規則：**任何含數值門檻、且會被用來觸發真實動作的產出（出場條件、觸發判定、警報閾值），落地後一律派 verifier 逐條驗引用**；自己新增的量化修飾詞（「連兩季」「跌破 X」）必須就地標記為自訂。
- [2026-07-15] 情境：判斷自訂 agent 的能力邊界｜錯誤：research subagent 憑「verifier 工具清單含 Bash」就斷定它無唯讀約束，沒讀 .claude/agents/verifier.md 正文（rule 5 早已禁止改檔/git 狀態）｜正解：agent 的實際約束寫在定義正文/frontmatter，tools 欄只列「能碰哪些工具」，不代表「怎麼用它們」｜規則：判斷自訂 agent 能做什麼，讀 .claude/agents/<name>.md 正文，不要只憑 tools 欄推斷。
- [2026-07-26] 情境：清 JEM 兩件「Mac 手動功課」（TDnet 開示、有報客戶表）｜錯誤：先假設「7/26 週報發現 runner 能直連行情 API」＝雲端 session 也能連日本站，直接 curl TDnet/EDINET｜事實：**兩者是不同執行環境**——那條 API 能力屬 GitHub Actions runner；雲端 session 的 agent proxy 對日本開示/財經站一律 CONNECT 403（實測：www.release.tdnet.info、api.edinet-fsa.go.jp、disclosure2.edinet-fsa.go.jp、irbank.net、kabutan、minkabu、finance.yahoo.co.jp、www.jem-net.co.jp、kabupro.jp，**WebFetch 走另一條 egress 也同樣 403**）。診斷法：`curl -sS --cacert /root/.ccr/ca-bundle.crt "$HTTPS_PROXY/__agentproxy/status"` 會列出 recentRelayFailures，直接看到是 gateway 政策拒絕還是連線問題，比反覆試 curl 快｜規則：**碰到「雲端抓不到」的站，不要反覆換 URL 硬試，也不要直接丟回 Mac 功課清單——先問「Actions runner 抓不抓得到」，抓得到就寫進資料橋**（本次做法：新增 `scripts/fetch_jp_disclosures.py`，側掛在 workflow 已在跑的 `fetch_backtest_ext.py` 末段＝不必動 `.github/workflows/` 也不必 actions:write）。搬進橋的判準：該資料會被重複需要（開示/客戶結構每季都要查）＋ runner 環境可達。
- [2026-07-26] 情境：主對話連續多輪研究｜事實：**WebSearch 有 session 級上限 200 次**，用罄後主對話與 subagent 都不能再搜（本 session 在第三個大研究任務中途撞到）｜規則：一個 session 要跑多個研究任務時，把搜尋密集的工作**優先派給 subagent 並在 prompt 裡限定「最多 N 次搜尋、先列必查清單再搜」**，主對話只做定點補查；接近上限時先把已得結果落檔，別讓額度耗盡卡死收尾。
- [2026-07-30] 情境：feature branch 的 PR 一直有 merge conflict，解完又冒新的（PR #31 累積 50 個衝突）｜錯誤：把「解衝突」當任務目標，逐檔解完再推——但 main 的排程**每天寫好幾次同一批資料檔**（dashboard/monitor/funnel 產出），每次解完就被下一個自動 commit 作廢，是追不上的跑步機｜正解：把 PR 改成**只含程式碼**（`git reset --hard <程式碼 commit>` 丟掉分支上的資料 commit、force-with-lease 推回），資料檔完全不碰，合併後由 main 的排程用新程式碼重生｜規則：**在這個 repo，長命 feature branch 的 PR 絕不夾帶 CI 會寫的路徑**（`*/data/**`、`docs/**`）。分支 CI 若也會 commit-back 到分支，記得在交付前把那些自動 commit reset 掉；結構上不共用路徑才是永久解，逐次解衝突不是。
- [2026-07-30] 情境：高頻（10 分鐘）輪詢型 workflow 要保存「上一輪狀態」以偵測異動｜錯誤傾向：沿用既有管線的 commit-back 模式落地狀態檔｜事實：一天 144 個 commit 會洗掉 git log，且與 main 的資料檔互相衝突｜正解：狀態走 `actions/cache/restore` + `actions/cache/save`（key 帶 `github.run_id`、restore-keys 用前綴抓最新一份），workflow 權限降成 `contents: read`｜規則：**高頻 workflow 的狀態一律走 Actions cache，不進版控**；並且設計成「cache 遺失＝只重建基準、不推播」，否則每次 cache 過期就把既有部位全報成新事件（假警報最大來源）。
- [2026-07-30] 情境：新寫的分析腳本要用 classify.parse_fills 的成交時間做「近 N 天」與「距今幾天」運算｜錯誤：假設時間戳是毫秒（Hyperliquid API 原始欄位確實是毫秒），寫成 `now_ms - days*86_400_000`｜事實：**parse_fills 內的 `_norm_ts` 已把時間正規化成 epoch 秒**，用毫秒運算會讓每個錢包的「最後成交距今」算成兩萬多天，全被「已停手」條件淘汰，掃描永遠回 0 個候選（離線測試的正向案例抓到）｜規則：**重用既有 parser 前先確認它輸出的單位/型別，不要用上游 API 的單位反推**；且離線測試一定要放一個「應該通過」的正向案例——只測「該被擋的有被擋」不會發現這種全域淘汰的缺陷。
- [2026-08-02] 情境：Serenity 週報重定價，照 `agents/loops/weekly-repricing-audit.md` 用 Yahoo Finance API 當寫死主源｜錯誤/事實：**該憲章的四個端點在 GitHub Actions runner 上全數回 HTTP 429 "Too Many Requests"**（`query1`／`query2` 的 `/v8/finance/chart`、`/v10/finance/quoteSummary`、連 `getcrumb` 都 429，換 UA／加 cookie jar 皆無效）——2026-07-26 建立的那條「主源」已失效，而憲章明文禁止退回 WebSearch，等於 loop 直接停擺｜正解：本 session 建立並逐檔實測通過的備援鏈——①**CNBC quote cache**：`https://quote.cnbc.com/quote-html-webservice/restQuote/symbolType/symbol?requestMethod=itv&noform=1&partnerId=2&fund=1&exthrs=1&output=json&symbols=<SYM>`，回傳 `source:"Exchange"`，附 `last`／`previous_day_closing`／`pe`(trailing)／`mktcapView`／`sharesout`／`yrhiprice`／`currencyCode`。代碼格式：美股裸代碼、日股 `6855.T-JP`、英股 `IQE-GB`、法股 `MRN-FR`、台股上市 `2408.TW-TW`、匯率 `JPY=`／`KRW=`／`TWD=`／`EUR=`／`GBP=`、指數 `.N225`／`.KS11`／`.SOX`。**三個坑：(a) 逗號批次查詢不支援**（回 `code:1`、`symbol` 欄變成整串逗號字串，會靜默拿不到任何資料）**(b) 查不到韓股**（`000660.KS-KR`／`A000660-KR` 皆 null）**(c) 查不到台股上櫃**（`6664.TWO-TW`／`3163.TWO-TW` 皆 null）②**韓股**：`https://api.finance.naver.com/siseJson.naver?symbol=<6碼>&requestType=1&startTime=YYYYMMDD&endTime=YYYYMMDD&timeframe=day`，回日線 OHLCV（單引號需轉雙引號才能 json.loads）③**台股（含上櫃）**：FinMind `https://api.finmindtrade.com/api/v4/data?dataset=TaiwanStockPrice&data_id=<code>&start_date=...` 無需 key，＋ TPEx 官方 `https://www.tpex.org.tw/openapi/v1/tpex_mainboard_quotes`（含 `Capitals`＝流通股數，可自算市值）作雙源交叉。**Stooq 已被 JS/PoW 挑戰擋死、kabutan 被 AWS WAF 擋、stockanalysis.com 的 `/api/quotes/s/<US>/` 可用但國際代碼路徑全 400、WSJ 被 DataDome 擋**——這四條不要再試｜規則：**重定價開工前先用一檔（例如 MU）打一次主源確認沒被限流，被擋就換上這條備援鏈，並用「三來源回傳的上週基準價 vs repo 記載的上週快照逐檔比對」當正確性驗收**（本次韓 6 檔、台 3 檔的 7/24 收盤與 watchlist 記載全對，才敢往下算）。
- [2026-08-02] 情境：崩跌週出現多檔買點同時命中，要決定「便宜就買」還是「等」｜事實：2026-07-29 週報在 19/36 檔同步 >15% 下跌的那一週跑出 7 個 🟢 觸發，當時判定「同源共同因子、不是 7 個獨立機會、紀律應收緊而非放寬、優先等 8 月初財報群」；**一週後（7/31 V 型反彈）7 檔裡有 3 檔的觸發依據自己消失**（Seikoh 加碼 B ¥17,900→¥18,770、Tamura ¥742→¥810 退出 ¥650–750、TSE ₩151,400→₩186,600 退出 <₩180k，框架外 RMBS 同樣退出 <$90）｜正解：等一週的成本是零；不等的成本是 3 筆買在恐慌價、隔週卻失去框架依據的部位｜規則：**同一週內出現 ≥3 檔觸發命中，先問「這幾檔是不是同一個宏觀因子的不同切面」——是的話把它當一個部位規模來配，並強制等下一個實體讀數（財報/營收）再執行**，不要按檔數配資。這條已從「本輪判讀」升格為常規紀律。
- [2026-08-09] 情境：Serenity 週報比對「價格 vs 觸發價」｜錯誤：把觸發價當成常數，一路沿用 watchlist 上寫死的價格帶｜事實：**觸發帶多半是「forward P/E × EPS 指引」算出來的，而 EPS 指引每季會被公司自己改寫**——2026-08-09 那週四檔同時上修，實測失準幅度：**Yamaichi「15× ≈ ¥6,700–7,200」用新 EPS ¥557.89 重算實為 ¥8,368（差 16–25%，而這一檔的偏差直接決定觸發響不響）**、**Kokusai「¥7,000–8,000 ＝ fwd ~40×」新 EPS 下實為 fwd 29–34×（出現「價格沒到但估值早就到了」的錯配）**、**Kohoku「25× ≈ ¥4,500–4,800」實為 ¥4,457**；四檔中只有 Towa 的「20× ≈ ¥1,850–2,000」驗算後仍正確｜規則：**每次全掃（每月第一個週日）用最新公司指引 EPS 重算全部價格型觸發帶，並在 watchlist 就地標註「本觸發價依據的 EPS 指引版本日期」**；財報週遇到任一標的上修/下修，該檔的觸發帶當週就要重算，不能等下次全掃。配套：**forward P/E 分兩類**——公司自家決算短信指引換算的標 `[推論-公司指引]`（來源是發行人原文，**可**作觸發依據），資料商估值標 `[推論]`（**不可**，見 2026-07-26 那條 Yahoo forwardPE 失真教訓）。
- [2026-08-09] 情境：在 GitHub Actions runner 上取日本公司財報數字｜錯誤傾向：沿用 2026-07-26 那條「雲端 session 對日本開示站一律 403」的結論，直接把日股財報丟進 Mac 手動功課｜事實：**Actions runner 對 TDnet 可直連**——`https://www.release.tdnet.info/inbs/I_list_<頁碼 001..>_<YYYYMMDD>.html`（適時開示一覽，一天分多頁）與 `https://www.release.tdnet.info/inbs/<docID>.pdf`（**決算短信 PDF 原文**）皆回 HTTP 200，`pip install --user pypdf` 後 `PdfReader(...).pages[0].extract_text()` 就能抽出売上高/営業利益/通期予想修正的表格數字。同一 runner 上 kabutan 403/405、minkabu 403、stooq JS challenge、Yahoo API 429 全部不通，**EDINET（有報）尚未實測**。一覽頁的 HTML 是 `<tr>` 內多個 `<td class="kjTime/kjCode/kjName/kjTitle">`，用單一大 regex 跨欄比對會抓不到，**要先 `re.split(r'<tr[^>]*>')` 再逐列解析 td**｜規則：**日本標的的財報數字一律以 TDnet 決算短信原文為主源，不用新聞轉述、不用搜尋 snippet**（本次一週內抓到 9 份，直接翻轉了 Yamaichi/Tamura/JCU 三檔的觸發判定，其中 Tamura 的「Q1 OP ≥¥14 億」用新聞是判不出來的）。更廣的規則：**「某站雲端擋」與「某站 runner 擋」是兩件事，每個新環境要各自實測一次，不要跨環境沿用封鎖結論**（這是 2026-07-26 那條的反向補充）。
- [2026-08-09] 情境：為「全名單同步崩跌」寫敘事歸因｜錯誤：2026-07-29 週報把日系標的的暴跌歸因於三件全球性事件（中國國產 DUV 量產、CXMT STAR 掛牌、SKH/Samsung Q2 miss），**漏掉了 7/28 的令和 8 年熊本地震（最大震度 7）**——TSMC 熊本 JASM 戶外避難＋二廠建設中斷、Renesas 川尻停產、Sony 半導體與三菱電機受影響；兩週後才在 JEM 的通期修正公告原文裡看到公司主動提及此事｜正解：三個原因都是全球性的，但**當週跌最凶的正是日系標的**——一組只含全球因子的歸因，解釋不了地域差異，這個缺口本身就是「還有東西沒找到」的訊號｜規則：**寫跨市場的崩跌/暴漲歸因時，先檢查「這份原因清單能不能解釋各市場的漲跌幅差異」**；若某個地區明顯偏離而清單裡沒有該地區獨有的因子，就標為「歸因不完整」並去找地區性事件（天災、匯率、當地政策、指數調整），不要用全球因子硬套。
- [2026-08-02] 情境：崩跌週市場流傳「記憶體現貨價崩跌」，要判斷持倉賣訊有沒有響｜錯誤傾向：財經媒體標題（FX Leaders 等）連續寫「spot-price freefall／spot price collapse」，很容易當成 T1 出場鐘（合約價 QoQ 轉負）的前哨而提前減碼｜事實：向 TrendForce 一手資料查證＝**自 4 月以來主流現貨價從未連續 2 週以上走平或下跌**，且 7 月底報告仍是「合約價續漲」（3Q26 傳統 DRAM +13–18% QoQ）；查到在跌的是**歐洲零售 DDR5 通道價**，不是合約層｜規則：**價格類的看空論據一律要求「哪一層價格」（合約／現貨／零售通道）＋「一手來源」＋「連續幾週」三件齊備才採用**；只有標題形容詞就標 `unverified`，不得作為賣訊或減碼依據。另一個同源教訓：本週 KOSPI 創史上最大單日漲幅（+17.91%）、SKH 漲停，但**同一天美國記憶體全跌**（MU −5.9%、SNDK −5.1%、DRAM ETF −3.8%）而 AI 互連在漲（COHR +5.6%、NVDA +2.9%）——**單一市場的極端漲跌不能代表資產類別的方向，跨市場同日比對才看得出資金到底買了什麼。**
